### ISSUE TITLE
Add some unique css to the active list item

### ISSUE THREAD

**Issue by Hkmu** [dmfrancisco/JS.coach#504] opened 2017-05-25 02:29 UTC
Can you add some css style to the item currently being viewed ? Thanks.
![menu](https://cloud.githubusercontent.com/assets/3169251/26433338/9dcf6790-4134-11e7-9f2d-0172106b584c.png)

**Comment by chookg** [comment] 2017-05-25 11:09
+1

**Comment by dmfrancisco** [comment] 2017-11-15 21:30
Thanks! Duplicate of #255.

**Closed as completed by dmfrancisco** 2017-11-15 21:30 UTC
Labels: feature request
